# -*- coding: utf-8 -*-
"""MINUTES MEETING GENERATOR.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJcb_MNnnIKtMzngYHie81DK1XVXOdzT
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma seperated): ")
agenda = input("Enter agenda points (comma seperated): ")
decisions = input("Enter decisions taken (comma seperated): ")
action_items = input("Enter action items (comma seperated): ")
prepared_by = input("Prepared by: ")

participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]

minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda": "; ".join(agenda_list),
    "Decisions Taken": "; ".join(decisions_list),
    "Action Items": "; ".join(actions_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")


}

df = pd.DataFrame(list(minutes.items()), columns=["Field","Details"])

print("\n Meeting Minutes Generated Successfully\n")
display(df)

df.to_csv("meeting_minutes.csv", index=False)
print("\n File saved as meeting_minutes.csv")