# -*- coding: utf-8 -*-
"""product review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHNhkbgdZhiPVEFS9SqofcFsaWZmtd5J
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

sentences = reviews.split(".")

pros = []
cons = []

for s in sentences :
  s = s.strip()
  if s == " ":
    continue

  result = sentiment(s)[0]

  if result["label"] == "POSITIVE":
    pros.append(s)
  elif result["label"] == "NEGATIVE":
    cons.append(s)

pros = pros[:2]
cons = cons[:2]

df = pd.DataFrame({
    "Pros" : pros,
    "Cons" : cons
})
df