# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyTNJ_KhdaGmr_TsMfF4NJ5_Uwne53tc
"""

!pip install sentence_transformers

from sentence_transformers import SentenceTransformer, util
model=SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter Text 1:")
text2 = input("Enter Text 2:")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1,embedding2)
print("\nSimilarity score:",round(float(similarity),2))
print("similarity level:High")
if similarity > 0.75:
  print("similarity level: High")
elif similarity > 0.4:
    print("similarity level: Meadium")
else:
     print("similarity level: low")