# -*- coding: utf-8 -*-
"""timetable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOy3oVEQKwuyZ4Lme_0C3cG4-601kW9H
"""

import pandas as pd
import random
print("TIMETABLE GENERATOR\n")
subject_input = input("enter subjects (comma separated): ")
days_input = input("enter days (comma separated): ")
periods_per_day = int(input("enter number of periods per day: "))
subjects = [s.strip() for s in subject_input.split(",") if s.strip()] # Changed 'subject' to 'subjects' and 'subjects_input' to 'subject_input'
days = [d.strip() for d in days_input.split(",") if d.strip()]
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
  print("Invalid input. Please try again.")
else:
  timetable = {}
  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day) # Changed 'random.choice' to 'random.choices' for multiple selections
  df = pd.DataFrame(timetable)
  df.index = [f"periods{i+1}" for i in range(periods_per_day)]
  print("\nTimetable Generated successfully.\n") # Fixed ']' to '\' and typo in 'successfully'
  display(df)
  df.to_csv("timetable.csv") # Changed 'to_csw' to 'to_csv' and '.cs' to '.csv'
  print("\ntimetable saved as timetable.csv")